"""init

Revision ID: 665e44bed9a6
Revises: 
Create Date: 2020-07-18 13:53:05.882305

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "665e44bed9a6"
down_revision = None
branch_labels = ("default",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paste",
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("contents", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=datetime.timezone.utc), nullable=False),
        sa.Column("visibility", sa.Enum("hidden", "public", name="visibility"), nullable=False),
        sa.Column("expire_at", sa.DateTime(), nullable=False),
        sa.Column("author_ip", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paste")
    # ### end Alembic commands ###
